name: build_pr

on:
  pull_request_target:
    branches: [ master ]

jobs:
  build_pr:
    if: ${{ github.event.pull_request.head.repo.full_name != github.repository }}
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3
      with:
        submodules: recursive
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
    - name: Checkout binaries
      uses: actions/checkout@v3
      with:
        repository: mkst/ctr-private
        token: ${{ secrets.PRIVATE_REPO_ACCESS }}
        path: binaries
    - name: Decrypt binaries
      run: echo ${{ secrets.CTR_BINARIES }} | openssl enc -d -aes-256-cbc -pass stdin -pbkdf2 -in binaries/bootloader.dat.aes -out bootloader.dat

    - name: Perform make extract
      uses: docker://ghcr.io/mkst/ctr:latest
      with:
        args: make extract
    - name: Perform make
      uses: docker://ghcr.io/mkst/ctr:latest
      env:
        WINEPREFIX: /ctr/.wine
      with:
        args: make all
